### ISSUE TITLE
Documentation/Clarity

### ISSUE THREAD

**Issue by aaronlippold** [mitre/saf_action#8]
In reading through the README a few things came to mind

- [ ] Document how the `with` fuction works and what `path` is relative to
- [ ] Example of how you might generate an output file from one task and use it in our action
- [ ] Document how you take the result and save it to a desired location
- [ ] Let's make one where we convert from one format to another and save it

This is one use case
```yaml
- name: Display our ${{ matrix.suite }} results summary
        uses: mitre/saf_action@v1
        with:
          command_string: 'view:summary -i spec/results/ec2_rhel-7_${{ matrix.suite }}.json'
      - name: Ensure the scan meets our ${{ matrix.suite }} results threshold
        uses: mitre/saf_action@v1
        with:
          command_string: 'validate:threshold -i spec/results/ec2_rhel-7_${{ matrix.suite }}.json -F ${{ matrix.suite }}.threshold.yml'
      - name: Save Test Result JSON
        uses: actions/upload-artifact@v2
        with:
          path: spec/results/
```
